#!/bin/bash

if [[ $1 == configure ]]
then
    declare -a cydia
    cydia=($CYDIA)
    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:reboot' >&${cydia[0]}"
    else
        echo "Please reboot your device."
    fi
fi

launchctl load /System/Library/LaunchDaemons/com.innoying.BashServer.plist 

